# -*- coding: utf-8 -*-
"""Decimal para binario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ez9_XDZL29AWChUWjgGHCigd5oZ856ls
"""

num = int (input("Digite um numero: "))
print(bin(num)[2:]) #[2:] para retirar o indicador de binario