# -*- coding: utf-8 -*-
"""MDC de dois numeros positivos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HNylGJKwkZikdtz9EGujx3y5emHg-PIO
"""

while True:                                                  
  num1 = int (input("Digite um numero inteiro: "))         
  num2 = int (input("Digite mais um numero inteiro: "))
  if (num1 or num2) > 0:
    break
  print("Digite outro numero: ") 
#Processamento  
mdc = num1  
while num1 % mdc != 0 or num2 % mdc != 0: 
        mdc = mdc - 1

print(mdc)